version: '3.8'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"

  app:
    build: .
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ""
      DB_DATABASE: torretimbo
    ports:
      - "8080:8080"

volumes:
  db-data:
